env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  AWS: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  import/extensions: 0
  no-param-reassign: ["error", { "props": false }]
